framework: mocha
tier: xlarge
postMerge:
  pattern:
    - "./test/index.ts"
preMerge:
  pattern:
    - "./test/index.ts"
preRun:
     command:
        - yarn install
        - yarn build:cjs
postRun:
     command:
        - yarn --version
version: 2.1
